name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write

env:
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_BOT_TOKEN }}

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    env:
      ILLA_URL: "https://illacloud.github.io"
      ILLA_BASE_URL: "/illa-website/"
      
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Crowdin CLI
        run: npm i -g @crowdin/cli

      - name: Check Crowdin
        run: crowdin -V

      - uses: pnpm/action-setup@v2
        with:
          version: 8.7.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Write translations
        run: pnpm run write-translations

      - name: Upload translations
        run: crowdin upload

      - name: Download translations
        run: crowdin download

      - name: Build website
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
